### ISSUE TITLE
$.address.wrap(true) breaks $(window).scroll()

### ISSUE THREAD

**Issue by jfromell** [asual/jquery-address#134]
I've tried to implement address with a site that uses "infinite scrolling", ajax content loading on page scroll.
It was working fine until i decided to use $.address.wrap(true), now the scroll event on the window won't fire.

Any ideas?

**Comment by asual** [comment]
This is very likely possible since the wrap option is forcing the creation of a div wrapper around the body content. I can think of a solution but it will require an override of the built-in jQuery method. A possible workaround for your case may be the use of something like $('body > div').scroll().

**Comment by jfromell** [comment]
That works. The next problem comes when trying to determine when the scroll is near the bottom of the document, as the document, the window and the body > div is all the same height. I might have to live with the page scrolling to the top after resetting the hash :P

**Comment by asual** [comment]
I'm not sure how you currently determine the scroll position but probably these values should do the job:
$('body > div').height()
$('body > div').scrollTop()
$('body > div').get(0).scrollHeight
