### ISSUE TITLE
Remove Path on Change

### ISSUE THREAD

**Issue by graygilmore** [asual/jquery-address#136]
I feel like I'm just not reading the documentation properly. If a user lands directly onto a permalink page, say:

http://mywebsite.com/post/this-is-a-title

and then they use the main navigation (where I have set up the .change events) they get this:

http://mywebsite.com/post/this-is-a-title#/other-page

What I want is for the permalink path to be replaced by the new link, so that they'd get this:

http://mywebsite.com/#/other-page

Is this part of the plugin? Am I terrible at reading? Any help would be greatly appreciated.

```
$("#main-navigation > li > a").on("click touchend", function() {

    $.address.value($(this).attr('href').replace(base, ''));

    return false;

});
```

**Comment by asual** [comment]
This is not possible in the way you describe it simply because when you use #hashes you cannot modify the standard /post/this-is-a-title part. So you end up modifying just the hash part of the location because every other change will require a page refresh.

The good thing is that HTML5 pushState is now almost everywhere and you can totally skip #hash links if you're starting a project with a perspective in mind.

**Comment by graygilmore** [comment]
Thanks - glad to know I wasn't doing something silly!
