### ISSUE TITLE
Scrolling to Top After Removing Value

### ISSUE THREAD

**Issue by graygilmore** [asual/jquery-address#145]
Using the latest code I cannot get `$.address.wrap(true);` to help with the scrolling to top issue.

Here's what my code looks like:

```
// jQuery Address
$.address.wrap(true);
$.address.init(function(event){
    if (event.value.indexOf('/post/') >= 0) {
        window.location = event.value;
    }
    $.address.value('/');
}).change(function(event) {  
    // do something
});
```

Basically, when a particular link gets clicked, that content gets loaded up in a modal box. When the modal box gets closed, the address updates to http://mysite.com/# which causes the browser to scroll directly to the top.

Based on this post: https://github.com/asual/jquery-address/issues/102 I thought I could use the address.wrap(true) but that doesn't seem to be getting the job done. Any other insight?

**Comment by graygilmore** [comment]
For anyone interested, this is what I've done:

```
// jQuery Address
$.address.init(function(event){
    if (event.value.indexOf('/post/') >= 0) {
        window.location = event.value;
    }
    $.address.value('/');
}).change(function(event) {  
    var scr = document.body.scrollTop;
    window.location.href = '#';
    document.body.scrollTop = scr;
});
```

The key here is what's inside the .change() function. I've also removed `$.address.wrap(true)` entirely.

**Comment by graygilmore** [comment]
Unforunately, that fix only worked in Chrome.

**Comment by asual** [comment]
The wrap option generates a DIV element around your content and this is how it fixes the scrolling problem. The provided tabs sample demonstrates how this happens.

Check if the DIV is properly generated. It can have different behavior in your case. Unfortunately it's hard to reproduce the problem without a complete example.

**Comment by b9chris** [comment]
Can you link to an example?

I bet your scrolling issue is caused by the content becoming short enough in the browser during the transition between "pages" that the browser jumps to the top. In fact, that's the only scenario I'm aware of where modern browsers will do this; otherwise just swapping content for one set to another that are both tall enough to have the scrollbar at the current position will just leave the scroll position be.

Your hack probably isn't working because of asynchrony; the call to force the scroll position is probably happening before the new, longer content actually appears. But, it's just a guess since there's no larger example posted here.

Either way this isn't a bug in jquery.address. This question probably belongs on StackOverflow - posting there with a more complete example will get you more help. This bug should really be closed.
