### ISSUE TITLE
JQuery Plugin doesn't work with JQuery Address

### ISSUE THREAD

**Issue by napster3000** [asual/jquery-address#41]
A JQuery plugin (raty) is in conflict with JQuery Address. If i delete JQuery Address it works. How do I run them both? 

Plz help me!

**Comment by asual** [comment]
I just tried adding the current version of jQuery Address to the Raty test page and I don't see any side effects. Can you post a sample or more info how the problem can be reproduced?

**Comment by hanialbeik** [comment]
i hope finiding this comment will help me solve my issue... 

what i'm trying to do is use SWFaddress (and JQuery Address) to load  Jquery Plugins inside a "called segment".  i'm gonna try to be as clear as possible..

Here is a sample script.

[ html ]
[ head ] 
[  SWF scripts and includes- Jquery and any other Plugin Scripts and CSS's }
[ /head ]
[body]
[div id=header] content i wanna keep on all the time - like menu [/div]

[div id=content] content i wanna change all the time [/div]

[div id=footer] footer content - keeps on all pages including a flash mp3 player[/div]
[/body]
[/html]

the SWFaddress & Jquery are EXACTLY as i downloaded it..  all i did was included the script and PHP file into the my main index and change a bit of the loading script to read PHP rather than XML... as it was on the DEMO. and its working exactly how i want it to be.
The Home Page has a jQuery Slider that will work only if i put it in the [div id=header] 
but when i have it loaded - by SWFaddress [div id=content] - it wont work..

SWFaddress loads from a source folder called DataSource/home.php or anyother page 

I managed to use EVAL() to run scripts that are included in the Loaded PHP file... such as [script]alert('hello')[/script]     BUT NOT [script src="somesource"][/script]

I also did a jQuery.getscript on some of the Source Files - it loaded the styling of the Javascript - but it never worked or animated. 

Note - the entire website doesn't have any flash content. 
Note - i'm a beginner in jQuery and Javascripts.

If this could be more helpful.. u can check out the current status of my website on
beta.thisfrequency.com 

i would really appreciate all the help and support on this....
